{
    "name": "Wallet Gateway",
    "summary": "Backoffice administrativo para sincronizar usuarios, cuentas y transferencias del gateway PagoFlex.",
    "version": "19.0.1.1.0",
    "category": "Tools",
    "author": "Hitofusion",
    "license": "LGPL-3",
    "depends": ["base", "base_setup", "web"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/incoming_transfer_commission_settings_data.xml",
        "views/menu_views.xml",
        "views/gateway_dashboard_views.xml",
        "views/gateway_dashboard_app_config_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/incoming_transfer_commission_settings_views.xml",
        "views/incoming_transfer_commission_distribution_rule_views.xml",
        "views/incoming_transfer_commission_push_wizard_views.xml",
        "views/user_incoming_commission_load_default_wizard_views.xml",
        "views/incoming_transfer_commission_account_views.xml",
        "views/incoming_transfer_commission_account_sync_wizard_views.xml",
        "views/negative_balance_limit_views.xml",
        "views/gateway_sync_job_views.xml",
        "views/gateway_sync_log_views.xml",
        "views/gateway_company_views.xml",
        "views/gateway_company_location_views.xml",
        "views/gateway_company_location_commission_agent_views.xml",
        "views/gateway_company_location_create_subaccount_wizard_views.xml",
        "views/gateway_bank_account_assignment_create_subaccount_wizard_views.xml",
        "views/company_membership_views.xml",
        "views/gateway_user_statement_line_views.xml",
        "views/gateway_user_statement_summary_views.xml",
        "views/gateway_user_views.xml",
        "views/company_commission_agent_views.xml",
        "views/gateway_bank_account_views.xml",
        "views/gateway_bank_movement_views.xml",
        "views/gateway_transfer_response_wizard_views.xml",
        "views/gateway_transfer_update_fecha_wizard_views.xml",
        "views/gateway_transfer_views.xml",
        "views/account_summary_report_views.xml",
        "views/commission_payable_report_views.xml",
        "views/daily_reference_report_views.xml",
        "views/reconciliation_control_views.xml",
        "data/sync_job_data.xml",
        "data/cron.xml",
        "data/cron_reconciliation.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "pagoflex_wallet_gateway/static/src/scss/gateway_dashboard.scss",
            "pagoflex_wallet_gateway/static/src/js/pf_realtime_charts_widget.js",
            "pagoflex_wallet_gateway/static/src/xml/pf_realtime_charts_widget.xml",
        ],
    },
    "images": ["static/description/icon.png"],
    "installable": True,
    "application": True,
}
