from . import agent_commission_service
from . import collection_services_commission
from . import collection_transaction_commission
from . import collection_dashboard_customer
from . import collection_transaction
from . import product_template
from . import res_partner
from . import list_name_account
from . import bank_statement
from . import account_bank_pagoflex
from . import collection_category
from . import bank_move_imported
