# -*- coding: utf-8 -*-
{
    "name": "Project Quotation Financing",
    "summary": "Gestión de cotizaciones y financiamiento de proyectos Odoo",
    "version": "17.0.1.0.0",
    "category": "Sales/CRM",
    "author": "Generated by ChatGPT",
    "website": "https://example.com",
    "license": "OPL-1",
    "depends": ["crm", "hr", "project", "sale", "mail"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/project_roles_demo.xml",
        "views/menus.xml",
        "views/crm_lead_views.xml",
        "views/project_quotation_views.xml",
        "views/project_financing_views.xml",
        "views/project_summary_views.xml",
        "views/reference_views.xml",
        "wizard/project_data_import_wizard_views.xml",
        "reports/project_summary_report.xml"
    ],
    "assets": {},
    "application": true,
    "installable": true,
    "description": "Módulo para calcular horas de implementación y financiamiento de proyectos, integrado al CRM. Flujo: CRM -> Cotización -> Financiamiento -> Resumen."
}